sudo: required
dist: trusty
before_install:
  - sudo apt-get update -q
  - sudo apt-get install -y cmake

# Enable C++ support
language: cpp

# Compiler selection
compiler:
  - gcc

# Build steps
script:
  - mkdir build
  - cd build
  - cmake .. && make
